---

- name: install postgresql package
  sudo: yes
  apt:
    pkg: "postgresql-{{ postgresql_version }}"
    state: installed
    update_cache: yes
    cache_valid_time: 3600

- name: install common postgres libraries
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items: common_packages
  sudo: yes
