---

- include: install.yml

- name: ensure database service is up
  service:
    name: postgresql
    state: started
  sudo: yes

# this needs to be here so that the master and slave nodes can access
# this variable in the common role for pecan config creation
- name: generate pseudo-random password for the app user database connection
  shell: python -c "exec 'import os; print os.urandom(30).encode(\'base64\')[:${length}]'"
  register: generated_app_user_password
  changed_when: false

- set_fact:
    postgresql_app_user_password: "{{ generated_app_user_password.stdout }}"

- include: users.yml
  when: "'postgresql_master' in group_names"

- include: configure.yml
  when: "'postgresql_master' in group_names"

- name: make {{ app_name }} database
  postgresql_db:
    name: "{{ app_name }}"
    owner: "{{ app_name }}"
    state: present
    login_user: postgres
  when: "'postgresql_master' in group_names"
  sudo_user: postgres
  sudo: yes

- include: standby.yml
  when: "'postgresql_standby' in group_names"
