---
- name: ensure database service is up
  service:
    name: postgresql
    state: started
  sudo: yes

- name: create the prod_db config file with the db password
  template:
    src: prod_db.py.j2
    dest: "{{ app_home }}/src/{{ app_name }}/prod_db.py"
  notify:
    - restart app

# this needs to be here because it needs the new db password
- name: create the prod alembic.ini file
  template:
    src: alembic-prod.ini.j2
    dest: "{{ app_home }}/src/{{ app_name }}/alembic-prod.ini"

- name: check if database for app needs populating
  # this should be configurable/optional in the playbook
  command: psql -t shaman -c "SELECT COUNT(*) FROM projects;"
  sudo_user: postgres
  sudo: yes
  register: database_is_populated
  ignore_errors: true
  changed_when: "database_is_populated.rc != 0"
  when: "'postgresql_master' in group_names"

- name: populate the database for {{ app_name }}
  when: "database_is_populated.rc == 1"
  command: "{{ app_home }}/bin/pecan populate {{ app_home }}/src/{{ app_name }}/prod.py"
  environment:
    ALEMBIC_CONFIG: "{{ app_home }}/src/{{ app_name }}/alembic-prod.ini"
  when: "'postgresql_master' in group_names"
