---
- name: ensure database service is up
  service:
    name: postgresql
    state: started
  sudo: yes

- name: generate pseudo-random password for the database connection
  shell: python -c "exec 'import os; print os.urandom(30).encode(\'base64\')[:${length}]'"
  register: generated_app_user_password
  changed_when: false

- set_fact:
    postgresql_app_user_password: "{{ generated_app_user_password.stdout }}"

- name: Make {{ app_name }} user
  postgresql_user:
    name: "{{ app_name }}"
    password: "{{ postgresql_app_user_password }}"
    role_attr_flags: "CREATEDB,LOGIN,NOSUPERUSER"
    state: "present"
    login_user: postgres
    db: "{{ app_name }}"
  sudo_user: postgres
  sudo: yes
  when: "'postgresql_master' in group_names"

- name: Make {{ app_name }} database
  postgresql_db:
    name: "{{ app_name }}"
    owner: "{{ app_name }}"
    state: present
    login_user: postgres
  sudo_user: postgres
  sudo: yes
  when: "'postgresql_master' in group_names"

- name: create the prod_db config file with the db password
  template:
    src: prod_db.py.j2
    dest: "{{ app_home }}/src/{{ app_name }}/prod_db.py"
  notify:
    - restart app

# this needs to be here because it needs the new db password
- name: create the prod alembic.ini file
  template:
    src: alembic-prod.ini.j2
    dest: "{{ app_home }}/src/{{ app_name }}/alembic-prod.ini"

- name: check if database for app needs populating
  # this should be configurable/optional in the playbook
  command: psql -t shaman -c "SELECT COUNT(*) FROM projects;"
  sudo_user: postgres
  sudo: yes
  register: database_is_populated
  ignore_errors: true
  changed_when: "database_is_populated.rc != 0"
  when: "'postgresql_master' in group_names"

- name: populate the database for {{ app_name }}
  when: "database_is_populated.rc == 1"
  command: "{{ app_home }}/bin/pecan populate {{ app_home }}/src/{{ app_name }}/prod.py"
  environment:
    ALEMBIC_CONFIG: "{{ app_home }}/src/{{ app_name }}/alembic-prod.ini"
  when: "'postgresql_master' in group_names"
