---

- name: reload systemd
  become: yes
  become: yes
  command: systemctl daemon-reload

- name: restart app
  become: yes
  service:
    name: shaman
    state: restarted
    enabled: yes

- name: restart nginx
  become: yes
  service:
    name: nginx
    state: restarted
