---

- hosts: all
  user: vagrant
  roles:
    - common
  vars:
     app_name: "shaman"
     use_ssl: true
     wsgi_file: wsgi.py
     wsgi_callable: application
     ansible_ssh_port: 22
     restart_app: true
     branch: "master"
     development_server: true
     fqdn: "localhost"
     api_user: "admin"
     api_key: "secret"
